import car1 from "../assets/cars/car1.svg";
import car2 from "../assets/cars/car2.svg";
import car3 from "../assets/cars/car3.svg";
import car4 from "../assets/cars/car4.svg";
import car5 from "../assets/cars/car5.svg";
import car6 from "../assets/cars/car6.svg";
import car7 from "../assets/cars/car7.svg";
import car8 from "../assets/cars/car8.svg";
import car9 from "../assets/cars/car9.svg";
import car10 from "../assets/cars/car10.svg";
import car11 from "../assets/cars/car11.svg";
import car12 from "../assets/cars/car12.svg";
import car13 from "../assets/cars/car13.svg";
import car14 from "../assets/cars/car14.svg";
import type { ICar } from "../types/type";
export const cars: ICar[] = [
  {
    id: 1,
    make: "Honda",
    model: "Civic",
    year: 2023,
    type: "Sedan",
    transmission: "Automatic",
    seats: 5,
    doors: 4,
    pricePerDay: 50,
    available: true,
    mileage: 8500,
    fuelType: "Gasoline",
    ac: true,
    image: car1,
    features: [
      "Bluetooth",
      "Backup Camera",
      "Apple CarPlay",
      "Adaptive Cruise Control",
    ],
  },
  {
    id: 2,
    make: "Toyota",
    model: "RAV4",
    year: 2024,
    type: "SUV",
    transmission: "Automatic",
    seats: 5,
    doors: 4,
    pricePerDay: 70,
    available: true,
    mileage: 4200,
    fuelType: "Gasoline",
    ac: true,
    image: car2,
    features: [
      "All-Wheel Drive",
      "Panoramic Sunroof",
      "Blind Spot Monitoring",
      "Keyless Entry",
    ],
  },
  {
    id: 3,
    make: "Ford",
    model: "F-150",
    year: 2023,
    type: "Pickup Truck",
    transmission: "Automatic",
    seats: 5,
    doors: 4,
    pricePerDay: 90,
    available: false,
    mileage: 15000,
    fuelType: "Gasoline",
    ac: true,
    image: car3,
    features: [
      "Towing Package",
      "Navigation System",
      "Heated Seats",
      "Backup Camera",
    ],
  },
  {
    id: 4,
    make: "Nissan",
    model: "Altima",
    year: 2022,
    type: "Sedan",
    transmission: "Automatic",
    seats: 5,
    doors: 4,
    pricePerDay: 48,
    available: true,
    mileage: 18000,
    fuelType: "Gasoline",
    ac: true,
    image: car4,
    features: ["Bluetooth", "Cruise Control", "Lane Departure Warning"],
  },
  {
    id: 5,
    make: "Chevrolet",
    model: "Tahoe",
    year: 2024,
    type: "SUV",
    transmission: "Automatic",
    seats: 7,
    doors: 4,
    pricePerDay: 110,
    available: true,
    mileage: 3000,
    fuelType: "Gasoline",
    ac: true,
    image: car5,
    features: ["Third Row Seating", "DVD Player", "Parking Sensors", "Sunroof"],
  },
  {
    id: 6,
    make: "Hyundai",
    model: "Elantra",
    year: 2023,
    type: "Sedan",
    transmission: "Automatic",
    seats: 5,
    doors: 4,
    pricePerDay: 42,
    available: true,
    mileage: 9800,
    fuelType: "Gasoline",
    ac: true,
    image: car6,
    features: ["Android Auto", "Backup Camera", "Keyless Entry"],
  },
  {
    id: 7,
    make: "BMW",
    model: "3 Series",
    year: 2023,
    type: "Luxury Sedan",
    transmission: "Automatic",
    seats: 5,
    doors: 4,
    pricePerDay: 120,
    available: true,
    mileage: 6000,
    fuelType: "Gasoline",
    ac: true,
    image: car7,
    features: [
      "Leather Seats",
      "Heated Seats",
      "Navigation System",
      "Premium Audio",
    ],
  },
  {
    id: 8,
    make: "Mercedes-Benz",
    model: "C-Class",
    year: 2024,
    type: "Luxury Sedan",
    transmission: "Automatic",
    seats: 5,
    doors: 4,
    pricePerDay: 130,
    available: true,
    mileage: 2500,
    fuelType: "Gasoline",
    ac: true,
    image: car8,
    features: [
      "Burmester Sound System",
      "Panoramic Roof",
      "Parking Assist",
      "Wireless Charging",
    ],
  },
  {
    id: 9,
    make: "Jeep",
    model: "Wrangler",
    year: 2023,
    type: "SUV",
    transmission: "Automatic",
    seats: 4,
    doors: 2,
    pricePerDay: 85,
    available: true,
    mileage: 11000,
    fuelType: "Gasoline",
    ac: true,
    image: car9,
    features: ["4x4", "Removable Top", "Off-Road Tires"],
  },
  {
    id: 10,
    make: "Tesla",
    model: "Model 3",
    year: 2024,
    type: "Electric Sedan",
    transmission: "Automatic",
    seats: 5,
    doors: 4,
    pricePerDay: 150,
    available: true,
    mileage: 1500,
    fuelType: "Electric",
    ac: true,
    image: car10,
    features: [
      "Autopilot",
      "Touchscreen Display",
      "Fast Charging",
      "Heated Seats",
    ],
  },
  {
    id: 11,
    make: "Volkswagen",
    model: "Jetta",
    year: 2022,
    type: "Sedan",
    transmission: "Automatic",
    seats: 5,
    doors: 4,
    pricePerDay: 40,
    available: true,
    mileage: 22000,
    fuelType: "Gasoline",
    ac: true,
    image: car11,
    features: ["Bluetooth", "Cruise Control"],
  },
  {
    id: 12,
    make: "Subaru",
    model: "Outback",
    year: 2023,
    type: "Wagon",
    transmission: "Automatic",
    seats: 5,
    doors: 4,
    pricePerDay: 65,
    available: true,
    mileage: 7000,
    fuelType: "Gasoline",
    ac: true,
    image: car12,
    features: ["All-Wheel Drive", "Roof Rack", "EyeSight Driver Assist"],
  },
  {
    id: 13,
    make: "Kia",
    model: "Seltos",
    year: 2024,
    type: "Crossover",
    transmission: "Automatic",
    seats: 5,
    doors: 4,
    pricePerDay: 60,
    available: true,
    mileage: 3500,
    fuelType: "Gasoline",
    ac: true,
    image: car13,
    features: ["Apple CarPlay", "Android Auto", "Rear Cross-Traffic Alert"],
  },
  {
    id: 14,
    make: "Mazda",
    model: "CX-5",
    year: 2023,
    type: "SUV",
    transmission: "Automatic",
    seats: 5,
    doors: 4,
    pricePerDay: 68,
    available: true,
    mileage: 5800,
    fuelType: "Gasoline",
    ac: true,
    image: car14,
    features: [
      "Heads-Up Display",
      "Bose Premium Audio",
      "Dynamic Stability Control",
    ],
  },
];
